MyBlog/MyBlog.AdminBlog/Controllers/ClassificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Application.ClassificationApplicationService;
using MyBlog.AdminBlog.ViewModel.Classifications;

namespace MyBlog.AdminBlog.Controllers
{
    public class ClassificationController : Controller
    {
        private readonly IClassificationApplicationService _classifyService;

        public ClassificationController(IClassificationApplicationService classifyService)
        {
            _classifyService = classifyService;
        }
        public IActionResult Index()
        {
            var result = _classifyService.Get()
                .Select(m => ClassificationViewModel
                .Convert(m.Id, m.Content, m.CreationTime, m.ModificationTime));
            return View(result);
        }

        [HttpPost]
        public IActionResult Create(string content)
        {
            _classifyService.Create(content);
            return RedirectToAction("index");
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var data = _classifyService.Get(id);
            var result = DeleteViewModel.Convert(data.Id, data.Content);
            return View("_Delete", result);
        }
        [HttpPost]
        public IActionResult DeleteComfirm(int id)
        {
            _classifyService.Remove(id);
            return View("_SuccessInfo");
        }
        [HttpPost]
        public IActionResult Update(int id)
        {
            var data = _classifyService.Get(id);
            var result = UpdateViewModel.Convert(data.Id, data.Content);
            return View("_Update", result);
        }
        [HttpPost]
        public IActionResult UpdateConfirm(UpdateViewModel update)
        {
            _classifyService.Update(update.Id, update.Content);
            return RedirectToAction("index");
        }
    }
}

MyBlog/MyBlog.AdminBlog/Views/Classification/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<MyBlog.AdminBlog.ViewModel.Classifications.ClassificationViewModel>
<section class="content-header">
    <h1>
        分类
        <small> @ViewData["Title"]</small>
        <button type="button" style="float:right" class="btn btn-primary" data-toggle="modal" data-target="#create-classification">添加</button>
    </h1>
</section>
<section class="content">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>内容</th>
                <th>创建时间</th>
                <th>修改时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Content</td>
                    <td>@item.CreateTime</td>
                    <td>@item.ModificationTime</td>
                    <td>
                        <from>
                            <a style="color:black" href="javaScript:void(0)" onclick="getUpdate(@item.Id)"><i class="glyphicon glyphicon-edit" title="编辑"></i></a>
                            <i>|</i>
                            <a style="color:red" href="javaScript:void(0)" onclick="getDelete(@item.Id)"><i class="glyphicon glyphicon-trash" title="删除"></i></a>
                        </from>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</section>

@Html.Partial("_Create")
<div id="showModel"></div>

<script>

    function getUpdate(id) {
        $.ajax({
            url: "/Classification/Update",
            method: "post",
            data: {
                id: id
            },
            success: function (data) {
                $("#showModel").html(data)
            }
        })
    }
    function getDelete(id){
        $.ajax({
            url: "/Classification/Delete",
            method:"post",
            data: {
                id:id
            },
            success: function (data) {
                $("#showModel").html(data)
            }
        })
    }
</script>

MyBlog/MyBlog.AdminBlog/Views/Classification/_Create.cshtml
<div class="modal fade" id="create-classification" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <form method="post" asp-controller="Classification" asp-action="Create">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">分类</h4>
                </div>
                <div class="modal-body">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1">内容</span>
                        <input type="text" class="form-control" placeholder="Content" aria-describedby="basic-addon1" id="content" name="content">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" onclick="cancle()">取消</button>
                    <button type="submit" class="btn btn-primary">保存</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    function cancle() {
        $("#content").val('');
    }
</script>

MyBlog/MyBlog.AdminBlog/Views/Classification/_Delete.cshtml
@{ 
    Layout = null;
}

@model MyBlog.AdminBlog.ViewModel.Classifications.DeleteViewModel


<div class="modal fade" id="myDeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <form>
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">确认删除</h4>
                </div>
                <div class="modal-body">
                    你确认要删除这个<span style="color:red">@(Model.Content)</span>分类么？？
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-danger" onclick="deleteComfirm(@Model.Id)">确认</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $("#myDeleteModal").modal("show");

    function deleteComfirm(id) {
            $.ajax({
                url: "/Classification/DeleteComfirm",
                method: "post",
                data: {
                    id: id
                },
                success: function (data) {
                    $("#showModel").html(data)
                }
            })
    }
</script>

MyBlog/MyBlog.AdminBlog/Views/Classification/_Update.cshtml
@model MyBlog.AdminBlog.ViewModel.Classifications.UpdateViewModel
@{ 
    Layout = null;
}
<div class="modal fade" id="update-classification" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <form method="post" asp-controller="Classification" asp-action="UpdateConfirm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">分类</h4>
                </div>
                <div class="modal-body">
                    <div class="input-group">
                        <input type="text" value="@(Model.Id)" hidden="hidden" name="id"/>
                        <span class="input-group-addon" id="basic-addon1">内容</span>
                        <input type="text" class="form-control"
                               placeholder="Content" 
                               aria-describedby="basic-addon1" id="content"
                               autocomplete="off" 
                               name="content" value="@Model.Content">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal" >取消</button>
                    <button type="submit" class="btn btn-primary">保存</button>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $("#update-classification").modal("show");
</script>